* Risk of rain mod to make it less overstimulating?
so close…
** TODO Debug SOTS AV Effect Options mod
** TODO Get AudioOverlapFix
* IDEA Category theory for quantum compilation
#+begin_example
            many functors
           ------------->
    U(2^n) -------------> Quantum Circuits
       |   ------------->      |
       |                       | eval
       |-----> U(dyadic) <-----|
 eval . comp
 (should be identical no matter what compilation strategy is used)
#+end_example

Study natural transforms between compilation functors? Initial & Final functors could be useful

/Entered on/ [2026-06-30 Tue 08:12]
* Bring lemon sticks camping?
* TODO Get toothpaste
* Do I have meltdowns?
 If so they would look like going blank and detaching. Shutdown. Causes for meltdowns:
- Feeling drained
- Sensory overload
- Cognitive overload (reading too many wikipages in quick succession)
Easier to proactively avoid situations than to react in the moment
* Maybe bring pancake mix camping?
* Morning routines
Structure can be really important/helpful for someone like me. I might actually be a fairly anxious person, and have just gotten really good at faking it and acting like I'm okay with "going with the flow". Try implementing a bit of a morning routine and see how you feel.
* TODO Readwise - notes on books and shit
* TODO Get Trader Joe’s coffee
