* Risk of rain mod to make it less overstimulating?
so close…
** TODO Debug SOTS AV Effect Options mod
** TODO Get AudioOverlapFix
* IDEA Category theory for quantum compilation
#+begin_example
            many functors
           ------------->
    U(2^n) -------------> Quantum Circuits
       |   ------------->      |
       |                       | eval
       |-----> U(dyadic) <-----|
 eval . comp
 (should be identical no matter what compilation strategy is used)
#+end_example

Study natural transforms between compilation functors? Initial & Final functors could be useful

/Entered on/ [2026-06-30 Tue 08:12]
* Bring lemon sticks camping?
* Do I have meltdowns?
 If so they would look like going blank and detaching. Shutdown. Causes for meltdowns:
- Feeling drained
- Sensory overload
- Cognitive overload (reading too many wikipages in quick succession)
Easier to proactively avoid situations than to react in the moment
* Maybe bring pancake mix camping?
* Morning routines
Structure can be really important/helpful for someone like me. I might actually be a fairly anxious person, and have just gotten really good at faking it and acting like I'm okay with "going with the flow". Try implementing a bit of a morning routine and see how you feel.
* TODO Readwise - notes on books and shit
* TODO Get coffee for babers
* TODO Cookwell app
It's finished!
/Entered on/ [2026-07-05 Sun 22:37]
* Can I just use beorg/organice for inbox/agenda/viewing main projects folder, and only really use zettelkasten stuff on computer?
I mean the original zettelkasten was a bunch of flash cards and filing cabinets...
* TODO Automate syncing with organice
Having to use git sync all the time is annoying. Would Dropbox be easier? Or some way to automatically git push/pull?
* TODO Messing with my config
- [ ] How to set fill-column wider?
- [ ] Make current line always centered? Do I even want that?
- [ ] ORG MODE
/Entered on/ [2026-07-07 Tue 23:47]
